Better creating GitHub issues
SAP/fosstars-rating-core pull request #613
Opened 2021-06-24 15:47 UTC by artem-smotrakov

WIP

Closes #603

2021-06-25 16:23 UTC, SebastianWolf-SAP requested changes
Really very elegant solution. I though I included the repository in the search, but obviously I didn't. That's embarrassing. :( 

Anyway, the refactoring and the new solution via a dedicated issue reporter work well - with one exception: The command-line argument is evaluated exactly the wrong way around. That should probably be fixed... ;)

2021-06-28 07:10 UTC, artem-smotrakov commented on src/main/java/com/sap/oss/phosphor/fosstars/tool/OssRulesOfPlayRatingHandler.java
> +    if (!commandLine.hasOption("create-issues")) {
Oops! Good catch!

2021-06-28 07:16 UTC, artem-smotrakov commented
> Really very elegant solution. I though I included the repository in the search, but obviously I didn't. That's embarrassing. :(
> 
> Anyway, the refactoring and the new solution via a dedicated issue reporter work well - with one exception: The command-line argument is evaluated exactly the wrong way around. That should probably be fixed... ;)

Thanks for the review and feedback @SebastianWolf-SAP ! I've fixed the bug you found.

2021-06-28 07:56 UTC, SebastianWolf-SAP approved these changes
Thanks for the fix - as I haven't found anything else on Friday and the tiny one is fixed, LGTM now ;)

2021-06-28 08:07 UTC, merged